[package]

name = "cubby"
version = "0.0.2"
authors = ["Chris Gill"]
description = "compartmentalized sync access and entity id system"
repository = "https://github.com/viperscape/cubby"
readme = "README.md"
license = "MIT"

[dependencies]
rand = "*"